### ISSUE TITLE
Parser isn't adding stats to DB file

### ISSUE THREAD

**Issue by AoZhora** [anthonyprintup/hunt-match-telemetry#29]
It seems the DB file stays stagnant after multiple plays - encounters go up but the kills/death tracker does not.

**Comment by AoZhora** [comment]
> It seems the DB file stays stagnant after multiple plays - encounters go up but the kills/death tracker does not.

I found the issue - it looks like the DB file is only tracking kills and deaths, but it also needs to track downs (Downed_by_me) and (Downed_Me).

Trying to see where I can add the code for the parser to add it to the DB file.

**Comment by anthonyprintup** [comment]
https://github.com/anthonyprintup/hunt-match-telemetry/blob/0282e91b4f2d8ee02c6ccb971059bd8c4521d954/src/hunt/attributes/match.py#L80-L83
The issue stems from the legacy code here, where before 1.11 fields such as "downed_by_me" didn't exist.
Thanks for the bug report, I'll push a fix when I can.
